# Generated by Django 4.0 on 2021-12-29 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do banco')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Codigo Bancario')),
                ('cheque_especial_inicial', models.FloatField(verbose_name='Limite Especial Inicial')),
                ('limite_inicial', models.FloatField(verbose_name='Limite Inicial')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('sexo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sexo')),
                ('tipodepessoa', models.CharField(max_length=30, verbose_name='Pessoa Fisica ou Juridica')),
                ('nomefantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia da Empresa')),
                ('cpfcnpj', models.CharField(max_length=15, unique=True, verbose_name='CPF ou CNPJ')),
                ('datanascimento', models.DateField(verbose_name='Data de Nasciemnto')),
                ('estadocivil', models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado Civil')),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidade')),
                ('profissao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=100)),
                ('agencia', models.CharField(blank=True, max_length=100, verbose_name='Agencia')),
                ('conta', models.CharField(blank=True, max_length=100, verbose_name='Conta')),
                ('saldo', models.FloatField(default=0, verbose_name='Saldo')),
                ('cheque_especial', models.FloatField(default=0, verbose_name='Cheque Especial')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.banco')),
                ('pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pessoa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('banco', 'pessoa', 'senha', 'agencia', 'conta', 'saldo', 'cheque_especial', 'data_cadastro'),
            },
        ),
    ]
